// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockIPAddress(arg1) {
  return window['go']['main']['App']['BlockIPAddress'](arg1);
}

export function GetSecurityAnalysis(arg1, arg2) {
  return window['go']['main']['App']['GetSecurityAnalysis'](arg1, arg2);
}

export function ScanDevicePorts(arg1) {
  return window['go']['main']['App']['ScanDevicePorts'](arg1);
}

export function StartLiveSniffing() {
  return window['go']['main']['App']['StartLiveSniffing']();
}

export function StartNetworkScan() {
  return window['go']['main']['App']['StartNetworkScan']();
}

export function StopSniffing() {
  return window['go']['main']['App']['StopSniffing']();
}
