// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {sniffer} from '../models';
import {bridge} from '../models';

export function BlockIPAddress(arg1:string):Promise<string>;

export function GetSecurityAnalysis(arg1:Array<scanner.PortResult>,arg2:Array<sniffer.PacketInfo>):Promise<bridge.AnalysisResult>;

export function ScanDevicePorts(arg1:string):Promise<Array<scanner.PortResult>>;

export function StartLiveSniffing():Promise<void>;

export function StartNetworkScan():Promise<Array<scanner.Device>>;

export function StopSniffing():Promise<void>;
